name: Build All Wheels (20 Environments)

on:
  workflow_dispatch:

jobs:
  placeholder:
    name: Placeholder job
    runs-on: ubuntu-latest
    
    steps:
    - name: Placeholder step
      run: |
        echo "This is a placeholder workflow for build-all-wheels.yml"
        echo "To be implemented in future PR"