name: Test Build (Single Environment)

on:
  workflow_dispatch:

jobs:
  placeholder:
    name: Placeholder job
    runs-on: ubuntu-latest
    
    steps:
    - name: Placeholder step
      run: |
        echo "This is a placeholder workflow for test-build.yml"
        echo "To be implemented in future PR"