name: Test Windows Wheel Build

on:
  workflow_dispatch:

jobs:
  test-windows:
    name: Test Windows wheel build - Python 3.11
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Set up Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: 1.75.0

    - name: Install system dependencies (Windows)
      shell: cmd
      run: |
        choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System'

    - name: Reconstruct family_names.txt
      run: |
        New-Item -ItemType Directory -Path "secret" -Force
        
        # Function to add newline if needed (PowerShell equivalent)
        function Add-NewlineIfNeeded($content) {
          if ($content -and !$content.EndsWith("`n") -and !$content.EndsWith("`r`n")) {
            return $content + "`n"
          }
          return $content
        }
        
        # Function to remove newline if needed (PowerShell equivalent)
        function Remove-NewlineIfNeeded($content) {
          if ($content -and ($content.EndsWith("`n") -or $content.EndsWith("`r`n"))) {
            return $content.TrimEnd("`r", "`n")
          }
          return $content
        }
        
        # Direct sequential output approach for perfect reconstruction (same as Linux)
        $result = ""
        $result += Add-NewlineIfNeeded $env:FAMILY_NAMES_PART_1
        $result += Add-NewlineIfNeeded $env:FAMILY_NAMES_PART_2
        $result += Add-NewlineIfNeeded $env:FAMILY_NAMES_PART_3
        $result += Add-NewlineIfNeeded $env:FAMILY_NAMES_PART_4
        $result += Add-NewlineIfNeeded $env:FAMILY_NAMES_PART_5
        $result += Add-NewlineIfNeeded $env:FAMILY_NAMES_PART_6
        $result += Add-NewlineIfNeeded $env:FAMILY_NAMES_PART_7
        $result += Remove-NewlineIfNeeded $env:FAMILY_NAMES_PART_8
        
        # Write to file without BOM and ensure no extra newline at end (UTF8 encoding like Linux)
        # Use WriteAllText with explicit content control to match Linux behavior
        $finalResult = $result.TrimEnd("`r", "`n")  # Ensure no trailing newlines
        [System.IO.File]::WriteAllText("secret\family_names.txt", $finalResult, [System.Text.UTF8Encoding]::new($false))
        
        # Copy to required locations
        Copy-Item "secret\family_names.txt" "namedivider-rs\family_names.txt"
        Copy-Item "secret\family_names.txt" "namedivider-rs\src\assets\family_names.txt"
      env:
        FAMILY_NAMES_PART_1: ${{ secrets.FAMILY_NAMES_PART_1 }}
        FAMILY_NAMES_PART_2: ${{ secrets.FAMILY_NAMES_PART_2 }}
        FAMILY_NAMES_PART_3: ${{ secrets.FAMILY_NAMES_PART_3 }}
        FAMILY_NAMES_PART_4: ${{ secrets.FAMILY_NAMES_PART_4 }}
        FAMILY_NAMES_PART_5: ${{ secrets.FAMILY_NAMES_PART_5 }}
        FAMILY_NAMES_PART_6: ${{ secrets.FAMILY_NAMES_PART_6 }}
        FAMILY_NAMES_PART_7: ${{ secrets.FAMILY_NAMES_PART_7 }}
        FAMILY_NAMES_PART_8: ${{ secrets.FAMILY_NAMES_PART_8 }}
      shell: powershell

    - name: Debug family_names.txt reconstruction
      run: |
        Write-Host "=== family_names.txt Debug Info ==="
        $fileExists = Test-Path "namedivider-rs\family_names.txt"
        Write-Host "File exists: $fileExists"
        
        if ($fileExists) {
          $fileSize = (Get-Item "namedivider-rs\family_names.txt").Length
          Write-Host "File size: $fileSize bytes"
          
          $lineCount = (Get-Content "namedivider-rs\family_names.txt" | Measure-Object -Line).Lines
          Write-Host "Line count: $lineCount"
          Write-Host "Expected line count: 39999"
          
          Write-Host "First 3 lines:"
          Get-Content "namedivider-rs\family_names.txt" | Select-Object -First 3
          
          Write-Host "Last 3 lines:"
          Get-Content "namedivider-rs\family_names.txt" | Select-Object -Last 3
        }
      shell: powershell

    - name: Verify family_names.txt reconstruction
      run: |
        # Use newline character counting (Linux wc -l equivalent) for consistent results
        $content = Get-Content "namedivider-rs\family_names.txt" -Raw
        $newlineChar = [char]10
        $lineCount = ($content.ToCharArray() | Where-Object { $_ -eq $newlineChar }).Count
        
        if ($lineCount -eq 39999) {
          Write-Host "[OK] File reconstruction successful ($lineCount lines, wc -l equivalent)"
        } else {
          Write-Host "[ERROR] File reconstruction failed: got $lineCount lines, expected 39999"
          Write-Host "Debug info: File ends with newline: $($content.EndsWith($newlineChar))"
          Write-Host "Debug info: File ends with CRLF: $($content.EndsWith([char]13 + [char]10))"
          exit 1
        }
      shell: powershell

    - name: Initialize Git submodules
      run: |
        Write-Host "=== Initializing Git submodules ==="
        git submodule update --init --recursive
        Write-Host "[OK] Submodules initialized"
      shell: powershell

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install maturin

    - name: Build wheel with maturin
      working-directory: python
      run: |
        python -m maturin build --release --out ../dist/

    - name: Upload wheel
      uses: actions/upload-artifact@v4
      with:
        name: wheel-windows-py3.11
        path: dist/*.whl

    - name: Test wheel installation
      env:
        RUST_BACKTRACE: 1
      run: |
        Write-Host "=== Testing wheel installation ==="
        Write-Host "Available wheels:"
        Get-ChildItem dist\*.whl
        
        Write-Host "Installing wheel:"
        Write-Host "Current directory: $(Get-Location)"
        Write-Host "Checking for wheel files..."
        
        try {
          $wheelFiles = Get-ChildItem dist\*.whl -ErrorAction Stop
          Write-Host "Found $($wheelFiles.Count) wheel file(s)"
          
          if ($wheelFiles -and $wheelFiles.Count -gt 0) {
            $wheelFile = $wheelFiles | Select-Object -First 1
            Write-Host "Selected wheel: $($wheelFile.FullName)"
            Write-Host "Installing wheel..."
            python -m pip install --force-reinstall $wheelFile.FullName
          } else {
            Write-Host "[ERROR] No wheel files found in array"
            exit 1
          }
        } catch {
          Write-Host "[ERROR] Failed to find wheel files: $($_.Exception.Message)"
          Write-Host "Directory contents:"
          Get-ChildItem dist\ -ErrorAction SilentlyContinue
          exit 1
        }
        
        Write-Host "Testing functionality..."
      shell: powershell

    - name: Test Python functionality with Japanese characters
      env:
        RUST_BACKTRACE: 1
      run: |
        echo "=== Testing namedivider functionality ==="
        
        # Test basic import
        python -c "import namedivider_rust; print('[OK] Module imported successfully')"
        
        # Test BasicNameDivider
        python -c "
        import namedivider_rust
        basic = namedivider_rust.BasicNameDivider()
        result = basic.divide_name('田中太郎')
        print(f'Basic result: {result}')
        assert str(result) == '田中 太郎'
        print('[OK] BasicNameDivider test passed')
        "
        
        # Test GBDTNameDivider  
        python -c "
        import namedivider_rust
        gbdt = namedivider_rust.GBDTNameDivider()
        result = gbdt.divide_name('佐藤花子')
        print(f'GBDT result: {result}')
        assert str(result) == '佐藤 花子'
        print('[OK] GBDTNameDivider test passed')
        "
        
        echo "[OK] All tests passed on Windows with Python 3.11!"
      shell: bash